source "https://rubygems.org"

gem "jekyll"
gem "webrick"
gem "jekyll-target-blank"
gem "jekyll-redirect-from"
gem "liquid_reading_time"
gem "liquid_pluralize"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
